name: SQL-PostgreSQL

services:
  postgres: 
    image: postgres:19beta4-alpine3.24
    container_name: gamestore_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gamestore
    ports:
      - "5431:5432"
    volumes:
      - ./db-data:/data

  pgadmin:
      image: dpage/pgadmin4:9.18
      container_name: gamestore_pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: 0arinaberdieva@gmail.com
        PGADMIN_DEFAULT_PASSWORD: psF7ZCvZeaKV!v5
      ports:
        - "5050:80"
      depends_on:
        - postgres  # name of postgres service 